/**
 * Simunye Skills SA - Practical Skills Catalogue & Interactive Vocational Simulations
 */

import { SkillItem, Simulation } from '../types';

export const SKILLS_CATALOGUE: SkillItem[] = [
  // --- PRACTICAL VOCATIONAL SKILLS ---
  {
    id: 'skill_plumbing_basic',
    title: 'Plumbing & Pipe Leak Maintenance',
    titleZu: 'Amapulani Okulungisa Amapayipi Nokuvuza Kwamanzi',
    category: 'plumbing',
    icon: 'Wrench',
    description: 'Diagnose leaking taps, shut off main water supplies, replace damaged rubber washers, and reassemble valves safely.',
    descriptionZu: 'Funda ukulungisa ompompi abavuzayo, uvale amanzi amakhulu, bese ushintsha ama-washer abolekile.',
    estimatedDataMB: 0.9,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['Water Isolation', 'Tap Disassembly', 'Washer Replacement', 'Pressure Testing'],
  },
  {
    id: 'skill_it_hardware_repair',
    title: 'PC Hardware Repair & Fault Diagnosis',
    titleZu: 'Ukulungisa Isikhompyutha Se-PC Neyingxenye Yaso',
    category: 'it_hardware',
    icon: 'Cpu',
    description: 'Troubleshoot dead computers, test power supply units (PSU), replace faulty RAM/storage, and follow anti-static safety.',
    descriptionZu: 'Thola ukuthi kungani ikhompyutha ingazamazami, uzoziqeqesha ekuvikeleni amagagasi nezinto zomshini.',
    estimatedDataMB: 0.8,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['Power Diagnostics', 'Anti-Static ESD Safety', 'RAM & PSU Replacement', 'POST Boot Test'],
  },
  {
    id: 'skill_spaza_practical_biz',
    title: 'Township Spaza Shop & Daily Ledger',
    titleZu: 'Ibhizinisi Lase-Spaza Nezimali Zansuku Zonke',
    category: 'entrepreneurship',
    icon: 'Store',
    description: 'Purchase wholesale stock in Rands (ZAR), calculate markup margins, serve difficult customers, and balance daily profit ledgers.',
    descriptionZu: 'Funda ukuthenga isitoko e-wholesale ngo-Rands, ukubala inzuzo, nokunakekela amakhasimende eKasi.',
    estimatedDataMB: 0.7,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['Wholesale Budgeting', 'Markup Margins', 'POS & Digital Pay', 'Daily Ledger Reconciliation'],
  },
  {
    id: 'skill_aviation_preflight',
    title: 'Light Aircraft Pre-Flight Safety Inspection',
    titleZu: 'Ukuhlola Indiza Ngaphambi Kokubhabha (Aviation Safety)',
    category: 'aviation',
    icon: 'Plane',
    description: 'Perform a pre-flight walkaround inspection on a light aircraft, check oil levels, sample fuel sumps for water, and sign flight logs.',
    descriptionZu: 'Hlola indiza ngaphambi kokuhamba emoyeni, hlola amafutha, amanzi kumpompi yezinto zikagesi ne-logbook.',
    estimatedDataMB: 0.9,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['Cockpit Pre-Checks', 'Fuel Water Sump Drain', 'Oil Level Dipstick', 'Logbook Sign-off'],
  },
  {
    id: 'skill_electrical_domestic',
    title: 'Domestic Electrical Wiring & DB Board',
    titleZu: 'Ukusetshenziswa Kwezintambo Kagesi eKhaya',
    category: 'electrical',
    icon: 'Zap',
    description: 'Inspect circuit breakers, perform isolator lockouts, test live wire voltage with multimeters, and wire standard SA plug tops.',
    descriptionZu: 'Hlola i-DB board, sebenzisa amamitha kagesi, uxhume ama-plug 3-pin ngokuphepha.',
    estimatedDataMB: 0.8,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['DB Board Lockout', 'Multimeter Voltage Test', 'SA 3-Pin Plug Wiring', 'Earth Leakage Test'],
  },
  {
    id: 'skill_automotive_basic',
    title: 'Automotive Engine Maintenance & Diagnostics',
    titleZu: 'Ukuhlola Nenjaniso YeMoto eGaraji',
    category: 'automotive',
    icon: 'Car',
    description: 'Check engine oil dipsticks, inspect brake fluid reservoirs, test battery terminal voltage, and replace spark plugs.',
    descriptionZu: 'Bheka amafutha enjini, amanzi amabhuleki, namabhethri emoto egaraji.',
    estimatedDataMB: 0.8,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['Fluid Level Checks', 'Battery Voltage Test', 'Spark Plug Swap', 'Brake Pad Inspection'],
  },
  {
    id: 'skill_agriculture_crop',
    title: 'Small-Scale Crop Farming & Soil Testing',
    titleZu: 'Ezokulima Nezesayensi Yenhlabathi',
    category: 'agriculture',
    icon: 'Sprout',
    description: 'Test soil pH levels, configure drip irrigation schedules, identify crop pests, and apply eco-friendly fertilizers.',
    descriptionZu: 'Hlola inhlabathi, uphakela amanzi ezitshalo, ugweme izinambuzane emasimini.',
    estimatedDataMB: 0.7,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['Soil pH Sampling', 'Drip Irrigation Setup', 'Natural Pest Control', 'Harvest Quality'],
  },
  {
    id: 'skill_construction_safety',
    title: 'Construction Site Scaffold & Bricklaying',
    titleZu: 'Ezokwakha Nemisebenzi Yasensambeni',
    category: 'construction',
    icon: 'HardHat',
    description: 'Inspect scaffold harness safety, mix mortar ratios (3:1 plaster sand), lay level brick courses, and enforce PPE rules.',
    descriptionZu: 'Funda izimfanelo zosimende, amabhuloki, nezokuphepha zasemsebenzini wokwakha.',
    estimatedDataMB: 0.8,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['PPE & Harness Checks', 'Mortar Mixing Ratios', 'Spirit Level Plumbing', 'Structural Curing'],
  },
  {
    id: 'skill_hospitality_service',
    title: 'Hospitality Food Safety & Customer Service',
    titleZu: 'Ezokudla Namahhotela e-SA',
    category: 'hospitality',
    icon: 'Utensils',
    description: 'Practice HACCP food hygiene temperatures, take restaurant table orders, handle customer complaints, and sanitize prep stations.',
    descriptionZu: 'Funda ezokuphepha kokudla, ukunakekela amakhasimende e-restaurant nasehotela.',
    estimatedDataMB: 0.6,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['HACCP Hygiene', 'POS Order Entry', 'De-escalation', 'Cross-Contamination Avoidance'],
  },
  {
    id: 'skill_workplace_safety',
    title: 'OHSA Workplace Safety & First Aid Basics',
    titleZu: 'Ezokuphepha Nokulimala eMsebenzini (OHSA)',
    category: 'workplace_safety',
    icon: 'ShieldCheck',
    description: 'Apply South African Occupational Health & Safety Act (OHSA) rules, conduct fire extinguisher triage, and render CPR.',
    descriptionZu: 'Ziqeqeshe emithethweni yezokuphepha ye-OHSA e-South Africa nebhande lokuqala lokulimala.',
    estimatedDataMB: 0.6,
    isOfflineReady: true,
    simulationsCount: 1,
    learningPath: ['OHSA Hazard ID', 'Fire Extinguisher PASS', 'First Aid CPR', 'Incident Reporting'],
  },
];

export const DEMO_SIMULATIONS: Record<string, Simulation> = {
  // ==========================================
  // SIMULATION 1: PLUMBING (LEAKING TAP REPAIR)
  // ==========================================
  'sim_plumbing_1': {
    id: 'sim_plumbing_1',
    skillId: 'skill_plumbing_basic',
    title: 'Residential Water Tap Leak Repair',
    titleZu: 'Ukulungisa Umphompi Ovuza Amanzi eKhaya',
    category: 'plumbing',
    difficulty: 'Beginner',
    difficultyZu: 'Owasemva',
    estimatedDataMB: 0.9,
    estimatedMinutes: 8,
    iconName: 'Wrench',
    description: 'A customer reports a tap dripping 2 liters per hour in Soweto. Inspect the leak, isolate the main water valve, replace the worn jumper washer, and restore water pressure.',
    descriptionZu: 'Umakhasimende ubika ukuthi umphompi ukhala amanzi. Hlola umphompi, uvale i-valve enkulu, ushintshise i-washer, bese uhlola ukusebenza.',
    realWorldContext: 'In South Africa, leaking taps waste millions of liters of potable municipal water annually. Knowing how to isolate mains and replace jumper washers is a core plumbing trade skill.',
    realWorldContextZu: 'Ompompi abavuzayo bamosha amanzi amaningi e-South Africa. Ukwazi ukuvala amanzi nokushintsha i-washer kuyisisekelo somsebenzi we-plumbing.',
    steps: [
      {
        stepId: 1,
        title: 'Step 1: Problem Inspection & Safety Isolation',
        titleZu: 'Inyathelo 1: Ukuhlola Inkinga Nokudlula Kokuphepha',
        objective: 'Inspect the dripping tap and select the correct tool/procedure to isolate the water supply before disassembly.',
        objectiveZu: 'Hlola umphompi ovuzayo bese uvala amanzi amakhulu ngaphambi kokuvula umphompi.',
        environmentName: 'Bathroom Sink Workstation',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_leaking_tap',
            name: 'Leaking Brass Tap',
            nameZu: 'Umphompi Wethusi Ovuza Amanzi',
            category: 'plumbing_fixture',
            status: 'faulty',
            label: 'Dripping Tap Nozzle',
            labelZu: 'Imbobo Yompompi Ovuza Amanzi',
            icon: 'Droplet',
            position: { x: 50, y: 35, z: 0 },
            inspectText: 'Tap is dripping steadily (approx 1 drop every 2 seconds). Water pressure is active.',
            inspectTextZu: 'Umphompi uvuza amadonsa amanzi njalo. Amanzi ayagobhoza.',
          },
          {
            id: 'obj_main_valve',
            name: 'Under-Sink Isolation Valve',
            nameZu: 'I-Valve Enkulu Yokuvala Amanzi',
            category: 'plumbing_fixture',
            status: 'active',
            label: 'Main Isolation Stopcock',
            labelZu: 'I-Stopcock Yokudlula Amanzi',
            icon: 'CircleDot',
            position: { x: 25, y: 70, z: 0 },
            inspectText: 'Main water stopcock valve under the sink. Currently turned OPEN.',
            inspectTextZu: 'I-valve enkulu engaphansi kukasinki. Isekuvulekeni.',
          },
        ],
        availableTools: [
          {
            id: 'tool_adjustable_wrench',
            name: 'Adjustable Shifting Wrench (Shifting Spanner)',
            nameZu: 'I-Wrench Eqondiswayo',
            category: 'tools',
            description: 'Used to loosen hex nuts and tap bonnets.',
            descriptionZu: 'Isetshenziswa ukuvula amantongomane omnkombo wompompi.',
            icon: 'Wrench',
          },
          {
            id: 'tool_stopcock_key',
            name: 'Isolation Valve Knob',
            nameZu: 'I-Knob Yokuvala Valve',
            category: 'safety',
            description: 'Rotates 90 degrees clockwise to isolate main water line.',
            descriptionZu: 'Izungeza nge-clockwise ukuvala amanzi.',
            icon: 'ShieldCheck',
            isCorrectForStep: true,
          },
          {
            id: 'tool_hammer',
            name: 'Claw Hammer',
            nameZu: 'Isando',
            category: 'tools',
            description: 'Heavy percussion tool.',
            descriptionZu: 'Isando sokushaya.',
            icon: 'Hammer',
          },
        ],
        requiredToolId: 'tool_stopcock_key',
        decisionPoint: {
          id: 'dec_plumb_1',
          title: 'What critical safety step must be performed BEFORE unscrewing the tap bonnet?',
          titleZu: 'Yini inyathelo lomsebenzi elibalulekile okufanele uliyenze ngaphambi kokuvula umphompi?',
          prompt: 'Unscrewing a tap while water pressure is active will cause a high-pressure water spray that floods the workspace.',
          promptZu: 'Ukuvula umphompi ngenkathi amanzi engavallwanga kuzodala ukuchitheka kwamanzi ngamandla.',
          choices: [
            {
              id: 'c_plumb_1_1',
              text: 'Turn the under-sink isolation valve 90° clockwise until fully CLOSED to shut off water supply.',
              textZu: 'Phendula i-isolation valve ibe ngu-90° clockwise ukuze uvale amanzi ngokuphelele.',
              isCorrect: true,
              isSafetyCritical: true,
              explanation: 'Water isolation is the mandatory safety rule #1 in plumbing. Always isolate pressure before breaking piping seals.',
              explanationZu: 'Ukudlulisa amanzi ngomsebenzi obalulekile nomthetho wokuqala kwezokudlulisa amanzi.',
              realWorldConsequence: 'Water pressure safely cut off! You can now disassemble the tap components cleanly without flooding.',
              realWorldConsequenceZu: 'Amanzi avaleke kahle! Manje usungakwazi ukuvula umphompi ngaphandle kokuchitha amanzi.',
              xpReward: 60,
            },
            {
              id: 'c_plumb_1_2',
              text: 'Immediately apply the adjustable wrench to the bonnet nut and twist counter-clockwise with maximum force.',
              textZu: 'Sebenzisa i-wrench ukuvula inathi ngamandla amakhulu ngokushesha.',
              isCorrect: false,
              isSafetyCritical: true,
              explanation: 'Failing to isolate water pressure causes a sudden 4-bar water burst flooding the room and damaging customer property.',
              explanationZu: 'Ukungavali amanzi kudala ukhukhula lwamanzi egumbini oludonsa ukulimala kwezinto.',
              realWorldConsequence: 'CRITICAL FAILURE: Room flooded with 30 liters of pressurized water! Customer property damaged.',
              realWorldConsequenceZu: 'UKUWA KWEZOKUPHEPHA: Igumbi ligcwele amanzi amaningi!',
              xpReward: 0,
            },
          ],
        },
        hint: 'Always isolate the water supply using the stopcock valve before using wrenches.',
        hintZu: 'Uvale amanzi nge-stopcock valve kuqala ngaphambi kokusebenzisa i-wrench.',
      },
      {
        stepId: 2,
        title: 'Step 2: Tap Disassembly & Washer Inspection',
        titleZu: 'Inyathelo 2: Ukuvula Umphompi Nokuhlola I-Washer',
        objective: 'Use the correct wrench to unscrew the tap bonnet, remove the internal spindle, and inspect the rubber jumper washer.',
        objectiveZu: 'Sebenzisa i-wrench evumelekile ukuvula i-bonnet wengaphakathi yompompi, ukhiphe i-spindle, ubheke i-washer.',
        environmentName: 'Disassembled Tap Spindle View',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_tap_bonnet',
            name: 'Tap Brass Bonnet Nut',
            nameZu: 'Inathi Ye-Bonnet Yethusi',
            category: 'plumbing_part',
            status: 'normal',
            label: '19mm Hex Nut Bonnet',
            labelZu: 'Inathi Ye-Hex 19mm',
            icon: 'Settings',
            position: { x: 45, y: 40, z: 0 },
            inspectText: '19mm hexagonal brass bonnet nut retaining the spindle.',
            inspectTextZu: 'Inathi ye-hexagonal ethusi ebambe i-spindle.',
          },
          {
            id: 'obj_damaged_washer',
            name: 'Worn Jumper Washer',
            nameZu: 'I-Washer Eyendile/Ebolekile',
            category: 'plumbing_part',
            status: 'faulty',
            label: '1/2 inch Black Rubber Washer (Cracked)',
            labelZu: 'I-Washer Enzima 1/2 inch (Eqhekeza)',
            icon: 'Circle',
            position: { x: 65, y: 55, z: 0 },
            inspectText: 'The 1/2 inch black rubber washer is brittle, cracked, and grooved, allowing water to bleed past the valve seat.',
            inspectTextZu: 'I-washer enzymayana 1/2 inch eqhekezekile eyenza amanzi adlule ngaphansi.',
          },
        ],
        availableTools: [
          {
            id: 'tool_adjustable_wrench',
            name: 'Adjustable Shifting Wrench',
            nameZu: 'I-Wrench Eqondiswayo',
            category: 'tools',
            description: 'Fits hex bonnet cleanly without stripping metal corners.',
            descriptionZu: 'Ingena kahle enathini ngaphandle kokuyonakalisa.',
            icon: 'Wrench',
            isCorrectForStep: true,
          },
          {
            id: 'tool_replacement_washer_12',
            name: 'New 1/2 inch Heavy-Duty Rubber Jumper Washer',
            nameZu: 'I-Washer Entsha Engu 1/2 inch',
            category: 'parts',
            description: 'Exact size match for residential South African pillar taps.',
            descriptionZu: 'Isayizi engena ngqo ku-pillar tap yase-South Africa.',
            icon: 'CheckCircle2',
            isCorrectForStep: true,
          },
          {
            id: 'tool_teflon_tape',
            name: 'PTFE Thread Sealant Tape',
            nameZu: 'I-Teflon Tape Yezintambo',
            category: 'parts',
            description: 'Seals threaded pipe joints.',
            descriptionZu: 'Inamathisela izintambo zamapayipi.',
            icon: 'RotateCcw',
          },
        ],
        requiredToolId: 'tool_replacement_washer_12',
        decisionPoint: {
          id: 'dec_plumb_2',
          title: 'You identified a cracked, grooved 1/2 inch rubber washer inside the spindle. What is the correct repair?',
          titleZu: 'Uthola i-washer ebolekile engu 1/2 inch ngaphakathi. Iyilungisa kanjani inkinga?',
          prompt: 'Inspect replacement parts carefully to match thread diameter and rubber hardness.',
          promptZu: 'Bheka izingxenye zokushintsha kahle ukuze usayizi uhambisane.',
          choices: [
            {
              id: 'c_plumb_2_1',
              text: 'Unclip old cracked washer, clean brass valve seat with cloth, and seat a brand new 1/2 inch rubber jumper washer.',
              textZu: 'Khipha i-washer ebolekile, usula endaweni yayo ngendwangu, bese ufaka i-washer entsha engu 1/2 inch.',
              isCorrect: true,
              explanation: 'Replacing worn washers with exact size matches restores watertight sealing against the brass valve seat.',
              explanationZu: 'Ukushintsha i-washer ebolekile nentsha yesisayizi esifanayo kuvimba ukuvuza kwamanzi ngokuphelele.',
              realWorldConsequence: 'Component fitted perfectly! Valve seat is clean and ready for leak-free reassembly.',
              realWorldConsequenceZu: 'I-washer ingene ngokuphelele! Indawo ihlanzekile no-ompompi usekulungele ukuvalwa.',
              xpReward: 60,
            },
            {
              id: 'c_plumb_2_2',
              text: 'Wrap duct tape around cracked old washer and put it back in spindle.',
              textZu: 'Songa i-tape kuyo i-washer ebolekile uwoyiphinda uyiye oyifake.',
              isCorrect: false,
              explanation: 'Duct tape deteriorates instantly under water pressure, causing tap to leak worse within hours.',
              explanationZu: 'I-duct tape iyabola phansi kwamanzi ngokushesha bese amanzi avuza kakhulu.',
              realWorldConsequence: 'Temporary patch fails immediately upon turning water back on.',
              realWorldConsequenceZu: 'I-tape iyawa ngokushesha uma kuvulwa amanzi.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Always replace worn rubber washers with new exact-size (1/2 inch) plumbing spares.',
        hintZu: 'Shintsha i-washer ebolekile ngenye entsha ye 1/2 inch.',
      },
      {
        stepId: 3,
        title: 'Step 3: Reassembly & Pressure Leak Verification',
        titleZu: 'Inyathelo 3: Ukuhlanganisa Nokuhlola Ukuvuza Kwamanzi',
        objective: 'Reassemble the tap spindle and bonnet, restore main water pressure, and verify zero leaks.',
        objectiveZu: 'Hlanganisa i-spindle ne-bonnet, uvule amanzi amakhulu, bese uqinisekisa ukuthi akukho amanzi avuzayo.',
        environmentName: 'Final Tap Leak Test Environment',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_restored_tap',
            name: 'Reassembled Brass Tap',
            nameZu: 'Umphompi Uhlanganiswe Kabusha',
            category: 'plumbing_fixture',
            status: 'resolved',
            label: 'Repaired Tap (Dry Nozzle)',
            labelZu: 'Umphompi Olungisiwe (Amanzi Amile)',
            icon: 'CheckCircle2',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Tap bonnet is snugged tight. Spindle turns smoothly.',
            inspectTextZu: 'Inathi iqine kahle. Spindle ijika kamnandi.',
          },
        ],
        availableTools: [
          {
            id: 'tool_stopcock_key',
            name: 'Isolation Valve Knob',
            nameZu: 'I-Knob Yokuvala Valve',
            category: 'safety',
            description: 'Turn counter-clockwise to restore main water pressure.',
            descriptionZu: 'Phendula ukuzovula amanzi amakhulu.',
            icon: 'ShieldCheck',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_stopcock_key',
        decisionPoint: {
          id: 'dec_plumb_3',
          title: 'How do you finalize and test the repair job?',
          titleZu: 'Uyivala kanjani futhi uyihlola kanjani inkinga emva kokulungisa?',
          prompt: 'Re-open the main isolation valve slowly while observing the tap nozzle.',
          promptZu: 'Vula i-isolation valve kancane ngenkathi ubheke embobeni yompompi.',
          choices: [
            {
              id: 'c_plumb_3_1',
              text: 'Re-open isolation valve slowly, turn tap handle ON/OFF twice to purge air, inspect nozzle for dry seal.',
              textZu: 'Vula i-isolation valve kancane, uvule/uvale umphompi kabili ukuxosha umoya, uhlole ukuthi akukho madonsa vuzayo.',
              isCorrect: true,
              explanation: 'Slow pressure restoration prevents hydraulic water hammer from bursting old pipe joints. Testing ON/OFF confirms washer seating.',
              explanationZu: 'Ukuvula kancane kuvimbela amandla amakhulu ezingoxini zamapayipi. Ukuvula/ukuvala kabili kuqinisekisa ukuhlala kwewasher.',
              realWorldConsequence: 'SUCCESS! Zero dripping detected. Job completed cleanly with 100% customer satisfaction.',
              realWorldConsequenceZu: 'IMPUMELELO! Akukho madonsa avuzayo. Umsebenzi ungeniswe kahle ngebheji lomsebenzi!',
              xpReward: 100,
            },
            {
              id: 'c_plumb_3_2',
              text: 'Leave main isolation valve CLOSED so the customer cannot turn on the tap.',
              textZu: 'Shaya uzishiyele i-isolation valve IVALEKILE ukuze umakhasimende angakwazi ukuvula umphompi.',
              isCorrect: false,
              explanation: 'Leaving isolation valves closed leaves the customer without running water in the household.',
              explanationZu: 'Ukushiya i-valve ivalekile kushiya umakhasimende engenamanzi ekhaya.',
              realWorldConsequence: 'Customer files complaint due to no running water.',
              realWorldConsequenceZu: 'Umakhasimende ufaka isikhalazo ngenxa yokungabikho kwamanzi.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Re-open the water isolation valve and cycle the tap handle to test airtight seal.',
        hintZu: 'Vula amanzi kancane uzoziqeqesha ekuvuleni nomphompi.',
      },
    ],
  },

  // ==========================================
  // SIMULATION 2: IT HARDWARE (PC WILL NOT START)
  // ==========================================
  'sim_it_hardware_1': {
    id: 'sim_it_hardware_1',
    skillId: 'skill_it_hardware_repair',
    title: 'PC No-Power & Memory Fault Diagnosis',
    titleZu: 'Ukulungisa Isikhompyutha Engazamazami Ngenxa Kagesi',
    category: 'it_hardware',
    difficulty: 'Intermediate',
    difficultyZu: 'Omaphakathi',
    estimatedDataMB: 0.8,
    estimatedMinutes: 9,
    iconName: 'Cpu',
    description: 'A customer brings an office desktop PC that gives zero signs of life when pressing the power button. Perform anti-static ESD grounding, diagnose PSU voltage faults, reseat RAM modules, and verify POST boot.',
    descriptionZu: 'Umakhasimende uletha i-PC engakhombisi zimpawu zamandla. Sebenzisa izinto zokuzivikela kagesi, hlola i-PSU, faka i-RAM kabusha, bese ungenisa i-POST boot.',
    realWorldContext: 'Computer hardware technicians must follow Electrostatic Discharge (ESD) safety protocols to avoid frying sensitive microprocessor chips while replacing Power Supplies or RAM.',
    realWorldContextZu: 'Abenzi bomsebenzi we-IT kufanele balandele izimfanelo zokuphepha kagesi (ESD) ukuze bangashisi amachip asikhompyutha lapho balungisa i-RAM ne-PSU.',
    steps: [
      {
        stepId: 1,
        title: 'Step 1: Electrostatic Safety & Power Disconnection',
        titleZu: 'Inyathelo 1: Ukuphepha Kagesi (ESD) Nokukhipha Iplagi',
        objective: 'Prepare the dead desktop PC workstation for safe internal hardware disassembly.',
        objectiveZu: 'Lungiselela i-PC yokulungisa ngokukhipha amandla nokusebenzisa umbhande kagesi (Anti-Static Wrist Strap).',
        environmentName: 'IT Repair Bench Environment',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_dead_pc',
            name: 'Dead Desktop PC Case',
            nameZu: 'Ikhompyutha I-PC Engazamazami',
            category: 'hardware',
            status: 'faulty',
            label: 'ATX PC Tower (Power LED OFF)',
            labelZu: 'I-PC ATX (Ilambu LiVALEKILE)',
            icon: 'Monitor',
            position: { x: 45, y: 35, z: 0 },
            inspectText: 'Pressing power button produces zero fan spin, no LED lights, no beep codes.',
            inspectTextZu: 'Ukuchofoza button kagesi akwenzi lutho, awekho amalambu akhanyayo.',
          },
          {
            id: 'obj_ac_cable',
            name: '230V AC Power Cord',
            nameZu: 'Intambo Kagesi 230V AC',
            category: 'power',
            status: 'normal',
            label: 'Main AC Wall Plug',
            labelZu: 'Iplagi Kagesi Yasewall',
            icon: 'Zap',
            position: { x: 20, y: 65, z: 0 },
            inspectText: 'Plugged into 230V wall socket.',
            inspectTextZu: 'Ixhunzwe ku-plagi kagesi kumpompi.',
          },
        ],
        availableTools: [
          {
            id: 'tool_esd_strap',
            name: 'Anti-Static ESD Wrist Strap',
            nameZu: 'Umbhande Kagesi Wokuzivikela (Anti-Static Strap)',
            category: 'safety',
            description: 'Grounds technician body static voltage (0V) to prevent frying CMOS microchips.',
            descriptionZu: 'Uvimbela kagesi wemizimba ekushiseni amachip.',
            icon: 'ShieldCheck',
            isCorrectForStep: true,
          },
          {
            id: 'tool_screwdriver_phillips',
            name: 'Phillips #2 Magnetic Screwdriver',
            nameZu: 'Isikulufoshanise #2',
            category: 'tools',
            description: 'Unscrews ATX side panel thumbscrews.',
            descriptionZu: 'Uvula izikulufu ze-PC.',
            icon: 'Settings',
          },
        ],
        requiredToolId: 'tool_esd_strap',
        decisionPoint: {
          id: 'dec_ithw_1',
          title: 'What mandatory safety precautions must be taken before touching internal computer motherboard components?',
          titleZu: 'Yini imithetho yokuphepha okufanele uyilandele ngaphambi kokuthinta i-motherboard yengaphakathi?',
          prompt: 'Human skin carries up to 3,000 Volts of static electricity which permanently destroys RAM and CPU silicon chips on contact.',
          promptZu: 'Isikhumba somuntu sinokuthwala kagesi static ongashisa i-RAM ne-CPU ngokushesha.',
          choices: [
            {
              id: 'c_ithw_1_1',
              text: 'Unplug AC power cord from wall AND attach anti-static ESD wrist strap grounded to bare metal chassis.',
              textZu: 'Khipha intambo kagesi emudulwini BESE ufaka umbhande we-anti-static ESD kuxhunywe ensimbini ye-PC.',
              isCorrect: true,
              isSafetyCritical: true,
              explanation: 'Disconnecting live AC power removes electrocution risks, while ESD grounding bleeds off body static potential before handling sensitive chips.',
              explanationZu: 'Ukukhipha kagesi nekuxhuma i-ESD kukhula amashansi omsebenzi omuhle ngaphandle kokushisa izinto.',
              realWorldConsequence: 'Workstation safely grounded! You can now remove side panel without risk of static chip fry.',
              realWorldConsequenceZu: 'I-PC nezandla zvikelwe kahle! Manje usungakwazi ukukhulula isiliva le-PC.',
              xpReward: 60,
            },
            {
              id: 'c_ithw_1_2',
              text: 'Keep 230V AC power cord plugged in while wearing wet rubber gloves and touching CPU pins.',
              textZu: 'Shiya kagesi u-230V uxhunyiwe ugqoke amagilavu anamansi uthinte izinaliti ze-CPU.',
              isCorrect: false,
              isSafetyCritical: true,
              explanation: 'Working inside a live 230V AC desktop power supply chassis risks lethal high-voltage electric shock.',
              explanationZu: 'Ukusebenza ngaphakathi kwi-PC enokagesi wempilo yengxube ephezulu kuno-230V kungadala ukufa.',
              realWorldConsequence: 'CRITICAL SAFETY HAZARD: Severe electric shock hazard detected!',
              realWorldConsequenceZu: 'UKUWA KWEZOKUPHEPHA: Ingozi kagesi osongela impilo!',
              xpReward: 0,
            },
          ],
        },
        hint: 'Unplug AC power and wear an anti-static ESD strap before touching motherboard chips.',
        hintZu: 'Khipha intambo kagesi ufake i-ESD wrist strap kuqala.',
      },
      {
        stepId: 2,
        title: 'Step 2: Component Voltage Diagnosis & Fault Isolation',
        titleZu: 'Inyathelo 2: Ukuhlola Kagesi We-PSU Ne-RAM Fault',
        objective: 'Test the Power Supply Unit (PSU) outputs and inspect motherboard status LEDs to pinpoint the failure.',
        objectiveZu: 'Hlola amandla e-Power Supply Unit (PSU) ne-RAM ukuze uthole inkinga yokungazamazami.',
        environmentName: 'Open ATX PC Case Interior',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_psu_unit',
            name: '450W ATX Power Supply Unit (PSU)',
            nameZu: 'I-Power Supply Unit (PSU) 450W',
            category: 'hardware',
            status: 'faulty',
            label: '450W PSU (Blown 12V Rail Capacitor)',
            labelZu: 'I-PSU 450W (Ishelwe I-Capacitor)',
            icon: 'BatteryCharging',
            position: { x: 30, y: 30, z: 0 },
            inspectText: 'Multimeter reading on 24-pin ATX green power-on pin shows 0.0V (0V DC rail output). Internal PSU fuse blown.',
            inspectTextZu: 'Imitha ibonisa ukuthi amandla kagesi e-PSU awawu 0.0V. I-fuse yengaphakathi ishelwe.',
          },
          {
            id: 'obj_ram_stick',
            name: '8GB DDR4 RAM Module',
            nameZu: ' I-RAM Module 8GB DDR4',
            category: 'hardware',
            status: 'warning',
            label: 'DDR4 RAM Stick (Unseated)',
            labelZu: 'I-RAM 8GB DDR4 (Ayingenanga Kahle)',
            icon: 'Cpu',
            position: { x: 60, y: 45, z: 0 },
            inspectText: 'RAM retention clips are unlatched on side B.',
            inspectTextZu: 'Izitika ze-RAM azivalekanga eceleni.',
          },
        ],
        availableTools: [
          {
            id: 'tool_multimeter',
            name: 'Digital Multimeter / PSU Tester',
            nameZu: 'I-Digital Multimeter Tester',
            category: 'tools',
            description: 'Measures DC rail voltages (+12V, +5V, +3.3V).',
            descriptionZu: 'Ibala amandla kagesi e-PSU.',
            icon: 'Zap',
            isCorrectForStep: true,
          },
          {
            id: 'tool_replacement_psu',
            name: 'New Certified 500W Modular ATX Power Supply',
            nameZu: 'I-PSU Entsha Yakulekhono 500W',
            category: 'parts',
            description: 'Replacement PSU with 80 Plus Bronze efficiency rating.',
            descriptionZu: 'I-PSU entsha elungele ukususa leyo eshelwe.',
            icon: 'CheckCircle2',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_replacement_psu',
        decisionPoint: {
          id: 'dec_ithw_2',
          title: 'Your multimeter confirmed 0.0V output on the blown PSU, and RAM clip B was loose. What is the correct replacement and installation procedure?',
          titleZu: 'Imitha iqinisekise ukuthi i-PSU ishelwe (0.0V). Iyilungisa kanjani inkinga?',
          prompt: 'Replace faulty hardware with rated compatible modules and ensure RAM latches click into place.',
          promptZu: 'Shintshanisa i-PSU eshelwe entsheni uqinise nendawana ye-RAM ide inqamuke kwi-click.',
          choices: [
            {
              id: 'c_ithw_2_1',
              text: 'Install new certified 500W PSU, connect 24-pin motherboard & 8-pin CPU power, and push RAM firmly until side latches CLICK closed.',
              textZu: 'Faka i-PSU entsha engu-500W, uxhume ama-cables e-motherboard ne-CPU, bese uphusha i-RAM ide inqamuke nge-CLICK.',
              isCorrect: true,
              explanation: 'Replacing blown PSUs with 80+ rated units ensures stable voltage, while firmly clicking RAM clips restores memory bus conductivity.',
              explanationZu: 'Ukufaka i-PSU entsha nekunqamukisa izipikili ze-RAM ezinhlangothini kunikeza i-PC amandla alungile nememori.',
              realWorldConsequence: 'New PSU installed and RAM seated securely! Ready for power-on diagnostic test.',
              realWorldConsequenceZu: 'I-PSU entsha ne-RAM sekufakwe ngendlela elungile! Sekulungele ukuhlolwa kagesi.',
              xpReward: 60,
            },
            {
              id: 'c_ithw_2_2',
              text: 'Solder copper wire across the blown PSU fuse and leave RAM loose.',
              textZu: 'Faka intambo ye-copper kwi-fuse eshelwe ye-PSU ushiye i-RAM ingaqinile.',
              isCorrect: false,
              explanation: 'Bypassing PSU internal fuses creates fire hazards and short circuits that destroy the motherboard and CPU.',
              explanationZu: 'Ukuxhuma intambo eceleni kwi-fuse eshelwe kudala umlilo osela i-PC yonke.',
              realWorldConsequence: 'Fire hazard! Short circuit destroys entire motherboard.',
              realWorldConsequenceZu: 'UMLILO! I-motherboard nesiphiwo sekhompyutha kusha kumpela.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Replace the blown PSU with a certified 500W unit and ensure RAM side clips CLICK shut.',
        hintZu: 'Faka i-PSU entsha ye-500W uqinisekise ukuthi i-RAM i-CLICK-ile.',
      },
      {
        stepId: 3,
        title: 'Step 3: Power Re-activation & POST Boot Verification',
        titleZu: 'Inyathelo 3: Ukuvula Kagesi Nokuhlola I-POST Boot',
        objective: 'Reconnect AC power cord, turn on PSU master switch, press front panel power button, and verify successful BIOS POST boot.',
        objectiveZu: 'Xhuma kabusha kagesi, uvule i-switch ye-PSU phezulu, ubheke ukuthi i-screen se-POST sicace kahle.',
        environmentName: 'Monitor POST Boot Display View',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_boot_monitor',
            name: 'LCD Monitor',
            nameZu: 'Isibuko Semonitha LCD',
            category: 'display',
            status: 'resolved',
            label: 'POST Screen: 8192 MB DDR4 OK',
            labelZu: 'POST Screen: 8192 MB DDR4 OK',
            icon: 'Monitor',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Display shows: "System BIOS v2.4. CPU: Intel Core i5 @ 3.2GHz. Memory OK: 8192 MB DDR4 @ 2666MHz. Booting Windows 11..."',
            inspectTextZu: 'Isibuko sibonisa ukuthi "Memory OK: 8192 MB DDR4. Isikhompyutha siqala ngokujwayelekile Windows 11..."',
          },
        ],
        availableTools: [
          {
            id: 'tool_esd_strap',
            name: 'Anti-Static ESD Wrist Strap',
            nameZu: 'Umbhande Kagesi Wokuzivikela',
            category: 'safety',
            description: 'Grounding strap.',
            descriptionZu: 'Umbhande wokuphepha.',
            icon: 'ShieldCheck',
          },
        ],
        decisionPoint: {
          id: 'dec_ithw_3',
          title: 'The computer turned on with fan spin, and the monitor displays "Memory OK: 8192MB DDR4". How do you finalize the repair?',
          titleZu: 'Isikhompyutha sivulekile, isibuko sibonisa "Memory OK". Uyivala kanjani inkinga ngokuphelele?',
          prompt: 'Re-attach side panel screws, tidy internal cables away from fans, and test operating system boot.',
          promptZu: 'Faka amaphasi e-PC unamathisele izikulufu, unamathisele izintambo kude ne-fan, uhlole ne-Windows.',
          choices: [
            {
              id: 'c_ithw_3_1',
              text: 'Tidy internal cables with zip ties away from CPU fan, re-attach chassis metal side panel, and verify Windows desktop load.',
              textZu: 'Bopha izintambo zibe kude ne-fan, faka isiliva le-PC, uthole nokuvuleka kwe-Windows desktop.',
              isCorrect: true,
              explanation: 'Cable management prevents wires from jamming CPU cooling fans, while sealing the chassis maintains targeted airflow cooling.',
              explanationZu: 'Ukubopha izintambo kude ne-fan kuvimbela ukufudumala kwe-CPU. Ukususa izintambo eziphambi kwe-fan kwenza i-PC inakekele izitshalo.',
              realWorldConsequence: 'JOB COMPLETE! PC boots into Windows smoothly in 12 seconds with quiet cooling. Customer issued repair receipt.',
              realWorldConsequenceZu: 'UMSEBENZI UPHELILE! Isikhompyutha sivuleka kahle evela nakwi-Windows ngemizuzwana engu-12. Umakhasimende uthola i-receipt!',
              xpReward: 100,
            },
            {
              id: 'c_ithw_3_2',
              text: 'Leave PC side panel completely off with loose wires hanging into the spinning CPU fan blades.',
              textZu: 'Shiya isiliva le-PC livulekile ngezintambo ezilenga ngaphakathi kwi-fan ejikayo.',
              isCorrect: false,
              explanation: 'Loose wires hitting high-speed CPU fan blades break fan blades and stall processor cooling, causing thermal shutdowns.',
              explanationZu: 'Izintambo ezilenga kwi-fan ziyayilimaza i-fan zibangele ukufudumala kwe-PC no-0V crash.',
              realWorldConsequence: 'Wire jams CPU fan. PC overheats and crashes after 5 minutes.',
              realWorldConsequenceZu: 'Intambo ivimba i-fan. PC iyafudumala iwe emva kwemizuzu emihlanu.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Tidy cables away from cooling fans and secure the chassis side panel.',
        hintZu: 'Hlanza izintambo kude ne-fan uvale namaphasi e-PC.',
      },
    ],
  },

  // ==========================================
  // SIMULATION 3: SMALL BUSINESS (SPAZA SHOP & LEDGER)
  // ==========================================
  'sim_spaza_mgmt_1': {
    id: 'sim_spaza_mgmt_1',
    skillId: 'skill_spaza_practical_biz',
    title: 'Thabo eKasi Spaza & Daily Ledger Operations',
    titleZu: 'Ukuphatha Isitolo Sasesilokishini Ngebhizinisi',
    category: 'entrepreneurship',
    difficulty: 'Intermediate',
    difficultyZu: 'Omaphakathi',
    estimatedDataMB: 0.7,
    estimatedMinutes: 10,
    iconName: 'Store',
    description: 'You are operating "Thabo’s Spaza" in Alexandra township with R1,500 starting capital. Manage wholesale inventory, navigate load-shedding fridge risks, handle customer payments, and balance daily cash profit ledgers.',
    descriptionZu: 'Uphatha isitolo sase-Alex ngemali yokuqala engu-R1,500. Bala ukuthenga isitoko, ukudla kagesi, nenzuzo encwadini yakho.',
    realWorldContext: 'Spaza shops generate over R180 billion in South Africa annually. Long-term profitability depends on managing perishable stock during power outages, fair pricing, and strict cash ledger accounting.',
    realWorldContextZu: 'Izitolo zaselokishini zingenisa izigidigidi zama-Rand e-South Africa. Inzuzo ibhekana nokuvikela ukudla emandleni kagesi neziyalo zokubala izimali.',
    steps: [
      {
        stepId: 1,
        title: 'Step 1: Metro Wholesale Stock Budgeting (R1,500 Budget)',
        titleZu: 'Inyathelo 1: Ukuthenga Isitoko e-Wholesale (Isabelomali R1,500)',
        objective: 'Select your weekly inventory at the wholesale warehouse for maximum township demand and profit.',
        objectiveZu: 'Khetha isitoko sasewholesale esizothengwa kakhulu eKasi ngemali engu-R1,500.',
        environmentName: 'Metro Cash & Carry Wholesale',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_stock_staples',
            name: 'Staple Foods (Mealie Meal 10kg & Bread)',
            nameZu: 'Ukudla Okuyisisekelo (Impuphu 10kg neBraedi)',
            category: 'inventory',
            status: 'normal',
            label: '5x Mealie Meal 10kg (R110 ea) + 20x Bread (R14 ea)',
            labelZu: '5x Impuphu 10kg (R110) + 20x Isinkwa (R14)',
            icon: 'Package',
            position: { x: 25, y: 35, z: 0 },
            inspectText: 'Fast-moving daily essentials. Total wholesale cost: R830.',
            inspectTextZu: 'Ukudla okuthengwa zonke izinsuku. Imali yonke ye-wholesale: R830.',
          },
          {
            id: 'obj_stock_airtime',
            name: 'Airtime & Prepaid Electricity Vouchers',
            nameZu: 'I-Airtime Nokhadana Kagesi',
            category: 'inventory',
            status: 'normal',
            label: 'MTN/Vodacom/Capitec Vouchers Pack',
            labelZu: 'Avocha e-Airtime e-R300',
            icon: 'Smartphone',
            position: { x: 55, y: 35, z: 0 },
            inspectText: 'Zero inventory space required, zero spoilage risk. Total wholesale cost: R300.',
            inspectTextZu: 'Azidli indawo, aziboli. Imali yazo: R300.',
          },
          {
            id: 'obj_stock_perishables',
            name: 'Fresh Meat & Dairy Pack',
            nameZu: 'Inyama Nobisi Olishisayo',
            category: 'inventory',
            status: 'warning',
            label: 'Fresh Polony & Milk (R370)',
            labelZu: 'Inyama Ye-Polony Nobisi (R370)',
            icon: 'ShoppingBag',
            position: { x: 80, y: 35, z: 0 },
            inspectText: 'High profit margin, BUT Stage 4 load-shedding is scheduled for 4 hours today! Your shop has no generator.',
            inspectTextZu: 'Inzuzo enkulu BUT load-shedding Stage 4 izoqala namuhla! Awunagenerator.',
          },
        ],
        availableTools: [
          {
            id: 'tool_ledger_book',
            name: 'Spaza Daily Cash Ledger & Calculator',
            nameZu: 'Incwadi Nezibalo Ze-Spaza',
            category: 'finance',
            description: 'Tracks wholesale cost subtotals vs remaining capital.',
            descriptionZu: 'Ibala ukuthi usebenzise malini nemali esele.',
            icon: 'DollarSign',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_ledger_book',
        decisionPoint: {
          id: 'dec_spaza_1',
          title: 'How should you allocate your R1,500 wholesale inventory budget?',
          titleZu: 'Uzoysabela kanjani imali yakho engu-R1,500 yesitoko?',
          prompt: 'Considering Stage 4 load-shedding scheduled for today without a backup generator, what is the smartest inventory purchase?',
          promptZu: 'Ngenxa ye-loadshedding Stage 4 eyenzeka namuhla, iyiphi indlela ehlakaniphile yokuthenga isitoko?',
          choices: [
            {
              id: 'c_spaza_1_1',
              text: 'Buy Staples (R830) + Airtime Vouchers (R300) + Dry Snacks & Cool Drinks (R370). Avoid heavy perishable meat without refrigeration.',
              textZu: 'Thenga ukudla okuyisisekelo (R830) + Airtime (R300) + Ama-Snacks neziphuzo (R370). Gwema inyama ebola kalula.',
              isCorrect: true,
              explanation: 'Smart inventory management accounts for infrastructure challenges like load-shedding. Dry goods and airtime don’t spoil during blackouts.',
              explanationZu: 'Ukuphatha okuhlakaniphile kucabangela i-loadshedding. Izinto ezomile ne-airtime aziboli ebumnyameni.',
              realWorldConsequence: 'You protect 100% of your capital from spoilage while stocking high-demand township items!',
              realWorldConsequenceZu: 'Uvikela R1,500 wakho zonke ezintweni ezingaboli ngenxa yakagesi!',
              xpReward: 60,
            },
            {
              id: 'c_spaza_1_2',
              text: 'Spend all R1,500 on fresh polony and unpasteurized milk because profit margin is 60%.',
              textZu: 'Sebenzisa yonke i-R1,500 kuthenga inyama nobisi ngoba kunenzuzo engu-60%.',
              isCorrect: false,
              explanation: 'Without a solar/generator backup, 4 hours of load-shedding in summer heat spoils milk and polony, causing total business bankruptcy.',
              explanationZu: 'Ngaphandle kwagenerator, i-loadshedding yezagiliji iyonakalisa inyama nobisi zonke zibole.',
              realWorldConsequence: 'Total stock loss of R1,500 within 24 hours. Business forced to close.',
              realWorldConsequenceZu: 'Ulahlekelwa u-R1,500 wonke ngaphansi kosuku olulodwa. Ibhizinisi liyavala.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Always evaluate perishable spoilage risks against load-shedding schedules.',
        hintZu: 'Bheka engcupheni yokubola kwempahla ngesikhathi se-loadshedding.',
      },
      {
        stepId: 2,
        title: 'Step 2: Retail Pricing & Fair Margin Calculation',
        titleZu: 'Inyathelo 2: Ukubala Inzuzo Intengo Ye-Spaza',
        objective: 'Set selling prices for White Bread (Wholesale R14) and Mealie Meal 10kg (Wholesale R110).',
        objectiveZu: 'Setha intengo yokudlulisa yesinkwa nempuphu.',
        environmentName: 'Thabo Spaza Counter & Price Board',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_price_board',
            name: 'Township Price Chalkboard',
            nameZu: 'Ibhodi Yentengo Ye-Spaza',
            category: 'business',
            status: 'normal',
            label: 'White Bread & Mealie Meal Price',
            labelZu: 'Intengo Yesinkwa Nempuphu',
            icon: 'DollarSign',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Supermarket 3km away sells Bread at R17. Local Spaza competitor sells Bread at R18.',
            inspectTextZu: 'I-Supermarket eduzane ithengisa isinkwa ngo-R17. Omunye eKasi uthengisa ngo-R18.',
          },
        ],
        availableTools: [
          {
            id: 'tool_ledger_book',
            name: 'Spaza Daily Cash Ledger & Calculator',
            nameZu: 'Incwadi Nezibalo Ze-Spaza',
            category: 'finance',
            description: 'Calculates 25% profit margin targets.',
            descriptionZu: 'Ibala inzuzo ewu-25%.',
            icon: 'DollarSign',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_ledger_book',
        decisionPoint: {
          id: 'dec_spaza_2',
          title: 'What retail price will you set for White Bread (Bought at R14 wholesale)?',
          titleZu: 'Iyiphi intengo ozoyisetha yesinkwa (Othenge ngo-R14 e-wholesale)?',
          prompt: 'You bought loaves at R14. You need a fair profit margin that keeps township customers loyal.',
          promptZu: 'Uthenge isinkwa ngo-R14. Unokuzikhethela entengweni yokuthengisa eKasi.',
          choices: [
            {
              id: 'c_spaza_2_1',
              text: 'Price Bread at R17.50 (25% markup, R3.50 profit per loaf).',
              textZu: 'Setha isinkwa ku-R17.50 (Inzuzo ngu-R3.50 ngesinkwa).',
              isCorrect: true,
              explanation: 'R17.50 offers a competitive price point lower than local competitors (R18) while delivering healthy gross profit margin.',
              explanationZu: 'R17.50 unikeza intengo enhle kakhulu ezuza amakhasimende kakhulu.',
              realWorldConsequence: 'Sells all 20 loaves quickly before end of day, earning R70 clean profit on bread alone!',
              realWorldConsequenceZu: 'Uthengisa zonke izinkwa ezingamashumi amabili, uthola R70 wenzuzo ecacile!',
              xpReward: 60,
            },
            {
              id: 'c_spaza_2_2',
              text: 'Price Bread at R35.00 (150% markup).',
              textZu: 'Setha isinkwa ku-R35.00 (Inzuzo engu-150%).',
              isCorrect: false,
              explanation: 'Extreme price gouging drives township customers away to nearby shops.',
              explanationZu: 'Ukukhuphula intengo ngokungaphambili kwenza amakhasimende abaleke emabili.',
              realWorldConsequence: 'Zero loaves sold. Bread goes stale after 3 days, causing financial loss.',
              realWorldConsequenceZu: 'Azikho izinkwa ezithengwayo. Isinkwa siyawola, ukulahlekelwa yimali.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Calculate a fair 20-30% markup that competes well with local township prices.',
        hintZu: 'Bala inzuzo ka 20-30% eyamukelekayo eKasi.',
      },
      {
        stepId: 3,
        title: 'Step 3: Customer Payment Handling & Digital Banking',
        titleZu: 'Inyathelo 3: Ukwamukela Izinkokhelo Nekhadi',
        objective: 'A customer buys R180 worth of groceries and asks to pay with Capitec card or SnapScan QR code.',
        objectiveZu: 'Umakhasimende uthenga ukudla kwe-R180, ucela ukubhadala nge-Capitec Card noma i-QR Code.',
        environmentName: 'Spaza Register & POS Machine',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_pos_machine',
            name: 'Mobile Card POS Machine',
            nameZu: 'Imoshini Yekhadi Ye-POS',
            category: 'finance',
            status: 'normal',
            label: 'Capitec / Yoco Card Terminal',
            labelZu: 'Imoshini e-Yoco / Capitec',
            icon: 'CreditCard',
            position: { x: 40, y: 50, z: 0 },
            inspectText: 'Connected via Bluetooth to mobile data. Accepts contactless tap-to-pay & SnapScan.',
            inspectTextZu: 'Ixhumeke nge-data kucingo. Yamukela amakhadi nezitika ze-SnapScan.',
          },
        ],
        availableTools: [
          {
            id: 'tool_pos_terminal',
            name: 'Yoco / Capitec Mobile Card Machine',
            nameZu: 'Imoshini Yekhadi Yoco / Capitec',
            category: 'finance',
            description: 'Processes digital card tap transactions safely.',
            descriptionZu: 'Inikeza indlela yokukhokha ngekhadi.',
            icon: 'CreditCard',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_pos_terminal',
        decisionPoint: {
          id: 'dec_spaza_3',
          title: 'How should you process the R180 payment safely?',
          titleZu: 'Uyemukela kanjani inkokhelo ka-R180 ngokuphepha?',
          prompt: 'Accepting digital card payments reduces cash on premises, minimizing burglary risks.',
          promptZu: 'Ukwamukela amakhadi kunciphisa imali engashisi esitolo nokwebiwa.',
          choices: [
            {
              id: 'c_spaza_3_1',
              text: 'Type R180 into POS terminal, confirm customer taps card, verify "Approved" slip before handing groceries.',
              textZu: 'Faka u-R180 emshini wekhadi, ikhasimende lithinte ikhadi, ubheke incwadi yokugunyaza ngaphambi kokunikeza ukudla.',
              isCorrect: true,
              explanation: 'Digital card payments settle directly into your business bank account, cutting down cash robbery risks in the township.',
              explanationZu: 'Ukukhokha ngekhadi kufaka imali ebhange ngqo, kuvikele ukubanjwa inkunzi.',
              realWorldConsequence: 'Transaction approved! Total week sales reached R2,180 with R680 net profit recorded in local ledger!',
              realWorldConsequenceZu: 'Inkokhelo yemukelwe! Inzuzo yonke ye-wiki ifike ku-R680!',
              xpReward: 100,
            },
            {
              id: 'c_spaza_3_2',
              text: 'Refuse card payment and tell customer to write their name in a debt notebook ("Matsale") for next month.',
              textZu: 'Nqaba ikhadi umtshele ukuthi abhale igama encwadini yezikweletu ("Matsale").',
              isCorrect: false,
              explanation: 'Uncontrolled customer credit ("matsale") destroys small business cash flow and causes unrecoverable bad debts.',
              explanationZu: 'Izikweletu ezingalawulwa ezitolo zibulala imali yebhizinisi.',
              realWorldConsequence: 'Over 40% of credit debts are never repaid, leading to insolvency.',
              realWorldConsequenceZu: 'Amashumi amane amaphesenti ezikweletu awakhokhwa, ibhizinisi liyawa.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Verify card authorization slips before handing over merchandise.',
        hintZu: 'Bheka ukuthi umshini uthi "Approved" ngaphambi kokunikeza impahla.',
      },
    ],
  },

  // ==========================================
  // SIMULATION 4: AVIATION (LIGHT AIRCRAFT PRE-FLIGHT)
  // ==========================================
  'sim_aviation_preflight_1': {
    id: 'sim_aviation_preflight_1',
    skillId: 'skill_aviation_preflight',
    title: 'Light Aircraft Pre-Flight Walkaround & Fuel Inspection',
    titleZu: 'Ukuhlola Indiza Ngaphambi Kokubhabha Nophethiloli',
    category: 'aviation',
    difficulty: 'Intermediate',
    difficultyZu: 'Omaphakathi',
    estimatedDataMB: 0.9,
    estimatedMinutes: 10,
    iconName: 'Plane',
    description: 'Perform a pre-flight walkaround inspection on a 4-seater trainer aircraft at Lanseria Airfield. Check cockpit controls, measure engine oil level on the dipstick, sample wing fuel sumps for water contamination, and verify flight logbooks.',
    descriptionZu: 'Hlola indiza ye-Lanseria Airfield. Hlola izinto zomshayeli wediza, amafutha enjini kwi-dipstick, nokudonsa amanzi kumpompi ye-fuel sump.',
    realWorldContext: 'In civil aviation worldwide (SACAA / ICAO), thorough pre-flight walkarounds prevent in-flight engine failures. Undetected water in aircraft fuel sumps causes engine starvation shortly after takeoff.',
    realWorldContextZu: 'Ngezomoya e-South Africa (SACAA), ukuhlola indiza kuqala kuvimbela ukufa kwenjini emoyeni. Amanzi ku-fuel azibulala injini ifika phezulu.',
    steps: [
      {
        stepId: 1,
        title: 'Step 1: Cockpit Interior Pre-Check & Control Lock Removal',
        titleZu: 'Inyathelo 1: Ukuhlola Ingaphakathi Yendiza Nengidi',
        objective: 'Verify ignition switches are OFF, remove control wheel lock, and check fuel selector valve position.',
        objectiveZu: 'Hlola ukuthi ukhadana kagesi UVALEKILE, ususe ingidi e-control wheel, ubheke i-fuel selector valve.',
        environmentName: 'Cessna Trainer Aircraft Cockpit',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_ignition_switch',
            name: 'Magneto Ignition Key Switch',
            nameZu: 'I-Key Switch Ye-Magneto Ignition',
            category: 'aviation_cockpit',
            status: 'normal',
            label: 'Magneto Switch (OFF)',
            labelZu: 'I-Magneto Switch (VALEKILE)',
            icon: 'Key',
            position: { x: 30, y: 40, z: 0 },
            inspectText: 'Key switch turned to OFF position. Mandatory safety state before turning propeller by hand!',
            inspectTextZu: 'Iki-switch ivalekile. Umthetho wokuphepha ngaphambi kokuthinta i-propeller!',
          },
          {
            id: 'obj_control_lock',
            name: 'Control Yoke Lock Pin',
            nameZu: 'Ingidi Ye-Control Yoke',
            category: 'aviation_cockpit',
            status: 'warning',
            label: 'Red Control Yoke Lock Pin (INSTALLED)',
            labelZu: 'Ingidi Ebovu Ye-Yoke (IFANENI)',
            icon: 'Lock',
            position: { x: 60, y: 55, z: 0 },
            inspectText: 'Red steel lock pin locking elevator and aileron control yoke in place.',
            inspectTextZu: 'Ingidi ebovu ebambe i-yoke ukuze ingazamazami emoyeni.',
          },
        ],
        availableTools: [
          {
            id: 'tool_logbook_checklist',
            name: 'Aircraft Pre-Flight Checklist & Logbook',
            nameZu: 'Incwadi Yokuhlola Indiza (Pre-Flight Checklist)',
            category: 'safety',
            description: 'SACAA mandatory step-by-step pilot walkaround guide.',
            descriptionZu: 'Incwadi yomthetho wokuhlola indiza.',
            icon: 'FileText',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_logbook_checklist',
        decisionPoint: {
          id: 'dec_av_1',
          title: 'What critical cockpit action must you take before stepping outside for the wing walkaround?',
          titleZu: 'Yini okufanele uyenze kwi-cockpit ngaphambi kokuzungeza amaphiko ediza?',
          prompt: 'Never touch a propeller on the ground unless Magneto switches are verified OFF and control lock is removed.',
          promptZu: 'Ungalingi uthinte i-propeller ngaphandle uma i-Magneto switch IVALEKILE nengidi isusiwe.',
          choices: [
            {
              id: 'c_av_1_1',
              text: 'Confirm Magnetos OFF, remove red control yoke lock pin, and set fuel selector valve to BOTH.',
              textZu: 'Qinisekisa ukuthi Magnetos IVALEKILE, ususe ingidi ebovu ye-yoke, usethe i-fuel selector ku-BOTH.',
              isCorrect: true,
              isSafetyCritical: true,
              explanation: 'Removing the control lock restores full motion to elevator and ailerons, while verifying Magneto OFF prevents accidental engine fire during propeller handling.',
              explanationZu: 'Ukukhipha ingidi kukhulula amaphiko endiza. Ukuhlola i-Magnetos kuvimbela indiza ukuthi iziqalele uma kuthintwa i-propeller.',
              realWorldConsequence: 'Cockpit secured safely! Flight controls unlocked and ready for exterior surface walkaround.',
              realWorldConsequenceZu: 'Ingaphakathi yendiza iphephile! Manje usungakwazi ukuzungeza amaphiko engaphandle.',
              xpReward: 60,
            },
            {
              id: 'c_av_1_2',
              text: 'Turn Master Switch ON and leave Magnetos on BOTH while stepping outside.',
              textZu: 'Vula i-Master Switch ushiye i-Magnetos ivulekile emandleni a-BOTH uhambe kwi-propeller.',
              isCorrect: false,
              isSafetyCritical: true,
              explanation: 'Leaving Magnetos ON while moving the propeller by hand can cause the engine to kick over and strike the technician lethally.',
              explanationZu: 'Ukushiya i-Magnetos ivulekile kungenza i-propeller iziqalele ikushaye ngamandla.',
              realWorldConsequence: 'CRITICAL AVIATION HAZARD: Propeller strike danger detected!',
              realWorldConsequenceZu: 'UKUWA KWEZOKUPHEPHA ZASEROYINI: Ingozi embi kakhulu ye-propeller!',
              xpReward: 0,
            },
          ],
        },
        hint: 'Verify Magnetos are OFF and remove the control lock pin.',
        hintZu: 'Qinisekisa ukuthi Magnetos IVALEKILE ususe ingidi.',
      },
      {
        stepId: 2,
        title: 'Step 2: Wing Fuel Sump Contamination Inspection',
        titleZu: 'Inyathelo 2: Ukudonsa Amanzi Ku-Fuel Sump Yamaphiko',
        objective: 'Sample aviation fuel from under-wing drain valves using a transparent fuel sampler cup to test for water contamination.',
        objectiveZu: 'Donsa amafutha kwi-fuel valve esaphikweni ngenkomishi elicwebile ukuhlola amanzi.',
        environmentName: 'Left Wing Fuel Tank Drain Station',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_fuel_drain_valve',
            name: 'Wing Fuel Tank Sump Valve',
            nameZu: 'I-Valve Ye-Fuel Sump ePhikweni',
            category: 'aviation_part',
            status: 'warning',
            label: 'Under-Wing Drain Quick-Valve',
            labelZu: 'I-Valve Yokudonsa ePhikweni',
            icon: 'Droplet',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Quick-drain valve under left wing root tank.',
            inspectTextZu: 'I-valve yokudonsa amafutha engaphansi kwephiko vulekile.',
          },
        ],
        availableTools: [
          {
            id: 'tool_fuel_sampler_cup',
            name: 'Transparent Aviation Fuel Sampler Glass Cup with Tester Pin',
            nameZu: 'Inkomishi Elicwebile Yokudonsa Amafutha (Fuel Sampler Cup)',
            category: 'tools',
            description: 'Transparent acrylic cup with center actuator pin to sample fuel and observe water bubbles.',
            descriptionZu: 'Inkomishi elimhlophe elicwebile elibonisa ama-bubble amanzi emafutheni.',
            icon: 'ShieldAlert',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_fuel_sampler_cup',
        decisionPoint: {
          id: 'dec_av_2',
          title: 'You drain 50ml of Avgas 100LL into the clear sampler cup. A distinct clear liquid layer sits at the bottom of the blue fuel. What is it?',
          titleZu: 'Udonsa amafutha ama-50ml. Uthola ingxenye ecwebile phansi kwamafutha aluhlaza. Yini leyo ngxenye?',
          prompt: 'Water is denser than aviation gasoline (Avgas 100LL) and sinks to the absolute bottom of the fuel tank sump.',
          promptZu: 'Amanzi anzima ukudlula amafutha Aviation gas (Avgas), ngakho ahlala phansi.',
          choices: [
            {
              id: 'c_av_2_1',
              text: 'It is WATER contamination! Continue draining sump until sample is 100% pure blue Avgas with zero water bubbles.',
              textZu: 'AMANZI lawa! Qhubeka ukudonsa le-sump valve kuze kusivele amafutha aluhlaza kuphela angenamanzi.',
              isCorrect: true,
              explanation: 'Water in fuel causes aircraft engine starvation during climb out. Draining until 100% pure fuel appears purges condensation accumulation.',
              explanationZu: 'Amanzi emafutheni abulala injini yendiza uma ibhabha phezulu. Ukudonsa kuze kuvele amafutha kuphela kusindisa impilo.',
              realWorldConsequence: 'Water completely purged from tank! Engine fuel supply verified 100% pure Avgas 100LL.',
              realWorldConsequenceZu: 'Amanzi akhishiwe ngokuphelele! Amafutha yendiza ahlanzekile acwebile.',
              xpReward: 60,
            },
            {
              id: 'c_av_2_2',
              text: 'Ignore the bottom layer and pour the water back into the top fuel tank cap.',
              textZu: 'Shaya indiva amanzi lawa uwayiphuce uphinde uwathele endizeni phezulu.',
              isCorrect: false,
              explanation: 'Pouring water back into aircraft fuel tanks causes complete engine failure immediately after takeoff rotation.',
              explanationZu: 'Ukuthela amanzi kabusha endizeni kucisha injini ifika emoyeni.',
              realWorldConsequence: 'Engine quits during takeoff climb. Forced emergency landing.',
              realWorldConsequenceZu: 'Injini iyacisha ibhabha emoyeni. Ukuba sengozini enkulu!',
              xpReward: 0,
            },
          ],
        },
        hint: 'Water sinks to the bottom of fuel cups. Drain until fuel is pure blue Avgas.',
        hintZu: 'Amanzi ahlala phansi nenkomishi. Donsa kuze kuvele amafutha kuphela.',
      },
      {
        stepId: 3,
        title: 'Step 3: Engine Oil Level & Flight Logbook Release',
        titleZu: 'Inyathelo 3: Ukuhlola Amafutha Enjini Ne-Logbook',
        objective: 'Check engine oil dipstick level (Must be between 6 and 8 quarts) and sign technical logbook prior to engine start.',
        objectiveZu: 'Bheka kwi-dipstick yamafutha enjini (kufanele abe phakathi kuka-6 kuya ku-8 quarts) usayine nencwadi yendiza.',
        environmentName: 'Engine Cowling Access Hatch',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_oil_dipstick',
            name: 'Engine Oil Dipstick',
            nameZu: 'I-Dipstick Yamafutha Enjini',
            category: 'aviation_part',
            status: 'normal',
            label: 'Oil Dipstick (Level: 7 Quarts)',
            labelZu: 'I-Dipstick Yamafutha (Level: 7 Quarts)',
            icon: 'CheckCircle2',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Oil level reads 7 quarts (Aviation 15W50). Clean color, level within 6-8 quart flight limits.',
            inspectTextZu: 'Amafutha e-dipstick ame ku-7 quarts. Umbala uhlanzekile no-level ulungile.',
          },
        ],
        availableTools: [
          {
            id: 'tool_logbook_checklist',
            name: 'Aircraft Pre-Flight Checklist & Logbook',
            nameZu: 'Incwadi Yokuhlola Indiza (Pre-Flight Logbook)',
            category: 'safety',
            description: 'Sign technical release form.',
            descriptionZu: 'Usayina ifomu lomthetho kwi-logbook.',
            icon: 'FileText',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_logbook_checklist',
        decisionPoint: {
          id: 'dec_av_3',
          title: 'Oil level is 7 quarts, fuel sumps are clear, and walkaround is complete. What is the final step?',
          titleZu: 'Amafutha awo-7 quarts, i-fuel ihlanzekile, ukuhlola kuphelile. Yini inyathelo lokugcina?',
          prompt: 'Record fuel quantity and oil levels, sign aircraft flight logbook, and prepare for startup.',
          promptZu: 'Faka amanani e-fuel ne-oil encwadini ye-logbook usayine.',
          choices: [
            {
              id: 'c_av_3_1',
              text: 'Sign aircraft technical logbook confirming pre-flight inspection complete, stow checklist, and request startup clearance.',
              textZu: 'Sayina i-logbook yendiza uqinisekisa ukuthi ukuhlola kuphele kahle, ubeke incwadi, ucele imvume yokuqala injini.',
              isCorrect: true,
              explanation: 'Official flight logbook release is legally binding civil aviation compliance confirming airworthiness before taking off.',
              explanationZu: 'Ukusayina i-logbook umthetho osemthethweni oqinisekisa ukuthi indiza ilungele ukubhabha emoyeni ngokuphepha.',
              realWorldConsequence: 'PRE-FLIGHT COMPLETE! Aircraft released airworthy. Learner earned Aviation Pre-Flight Micro-Credential Badge!',
              realWorldConsequenceZu: 'UKUHLOLA KUPHELE KAHLE! Indiza yamukelekile ukubhabha. Uzuze ibheji le-Aviation Pre-Flight!',
              xpReward: 100,
            },
            {
              id: 'c_av_3_2',
              text: 'Discard logbook in trash bin and fly without recording oil level.',
              textZu: 'Lahla incwadi kwi-bin ubhabhe ngaphandle kokusayina.',
              isCorrect: false,
              explanation: 'Flying without signed logbook release violates SACAA airworthiness laws.',
              explanationZu: 'Ukubhabha ngaphandle kokusayina i-logbook kwephula umthetho waseroyini.',
              realWorldConsequence: 'Flight grounded by Civil Aviation Inspector.',
              realWorldConsequenceZu: 'Indiza iyamiswa yiziphathi-mandla zase-Civil Aviation.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Sign the technical logbook to certify aircraft airworthiness.',
        hintZu: 'Sayina i-logbook yendiza ngaphambi kokubhabha.',
      },
    ],
  },

  // ==========================================
  // SIMULATION 5: ELECTRICAL (DB BOARD CIRCUIT FAULT)
  // ==========================================
  'sim_electrical_1': {
    id: 'sim_electrical_1',
    skillId: 'skill_electrical_domestic',
    title: 'Domestic Electrical DB Board & Circuit Fault Repair',
    titleZu: 'Ukuhlola i-DB Board Ne-Circuit Breaker Kagesi',
    category: 'electrical',
    difficulty: 'Intermediate',
    difficultyZu: 'Omaphakathi',
    estimatedDataMB: 0.8,
    estimatedMinutes: 9,
    iconName: 'Zap',
    description: 'A 20A circuit breaker trips repeatedly in a residential DB board when appliances are connected. Perform safety lockout, test live voltage with a multimeter, identify the faulty short-circuit appliance, and safely restore power.',
    descriptionZu: 'I-circuit breaker ewu-20A iyazicisha lapho kuxhunywa izinto kagesi. Sebenzisa i-multimeter, uvale i-isolator, uthole into edala i-short circuit, bese uvula kagesi ngokuphepha.',
    realWorldContext: 'ELECTRICAL SAFETY WARNING: High-voltage AC electrical systems carry lethal electrocution risks. Always perform Lockout-Tagout (LOTO) and zero-voltage multimeter verification. This simulation provides conceptual training and does NOT replace supervised electrical apprenticeship.',
    realWorldContextZu: 'ISEXWAYISO SOKUPHEPHA: Kagesi osemudulwini unengulube yokukubulala. Hlola njalo ngemitha kuqala. Simulation ayikuthathi indawo yokuqeqeshwa ngumfundisi kagesi.',
    steps: [
      {
        stepId: 1,
        title: 'Step 1: Main Isolator Switch Lockout & Safety Isolation',
        titleZu: 'Inyathelo 1: Ukuvala I-Isolator Enkulu Ye-DB Board',
        objective: 'Safely isolate the main DB board incoming supply and attach a lockout tag before removing panel covers.',
        objectiveZu: 'Vala i-switch enkulu ye-DB board ufake no-Lockout Tag ngaphambi kokuvula isiliva.',
        environmentName: 'Domestic DB Board Workstation',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_main_isolator',
            name: '63A Double-Pole Main Isolator Switch',
            nameZu: 'I-Isolator Enkulu 63A Double-Pole',
            category: 'electrical_fixture',
            status: 'active',
            label: 'Main DB Isolator (Position: UP / ON)',
            labelZu: 'I-Isolator Enkulu (Ikho phezulu / VULEKILE)',
            icon: 'Zap',
            position: { x: 30, y: 35, z: 0 },
            inspectText: 'Main 63A double-pole isolator switch feeding the DB board busbar. Currently ON.',
            inspectTextZu: 'I-switch enkulu efaka kagesi kwi-DB board. Isathembele phezulu.',
          },
          {
            id: 'obj_tripped_cb',
            name: '20A Plug Circuit Breaker (Tripped)',
            nameZu: 'I-Circuit Breaker 20A (Iyazicisha)',
            category: 'electrical_fixture',
            status: 'faulty',
            label: '20A Plug Circuit CB (Position: CENTER TRIPPED)',
            labelZu: 'I-CB 20A (Isephakathi / TRIPPED)',
            icon: 'AlertTriangle',
            position: { x: 60, y: 50, z: 0 },
            inspectText: '20A plug circuit breaker has tripped to center position due to short circuit overload.',
            inspectTextZu: 'I-circuit breaker ikhumuke yahlala phakathi ngenxa ye-short circuit.',
          },
        ],
        availableTools: [
          {
            id: 'tool_lockout_padlock',
            name: 'LOTO Safety Lockout Hasps & Red Padlock',
            nameZu: 'Ingidi Ye-Lockout Ebovu (LOTO Safety)',
            category: 'safety',
            description: 'Prevents accidental re-energization of circuit while servicing DB board.',
            descriptionZu: 'Ivimbela umuntu ukuthi avule kagesi ungazelele.',
            icon: 'ShieldCheck',
            isCorrectForStep: true,
          },
          {
            id: 'tool_insulated_screwdriver',
            name: '1000V Insulated Screwdriver Set',
            nameZu: 'Isikulufoshanise Esivikelwe (1000V Insulated)',
            category: 'tools',
            description: 'VDE certified insulated handles rated for electrical panel maintenance.',
            descriptionZu: 'Isikulufoshanise sokuvikela kagesi wama-1000V.',
            icon: 'Wrench',
          },
        ],
        requiredToolId: 'tool_lockout_padlock',
        decisionPoint: {
          id: 'dec_elec_1',
          title: 'What critical safety step must be taken BEFORE touching DB busbar connections?',
          titleZu: 'Yini inyathelo lomsebenzi okufanele uliyenze ngaphambi kokuthinta i-DB board?',
          prompt: 'Never open live DB board covers without flipping main isolator OFF and applying Lockout Tagout (LOTO).',
          promptZu: 'Ungavuli i-DB board ngaphandle kokudlulisa i-isolator ne-Lockout Tag.',
          choices: [
            {
              id: 'c_elec_1_1',
              text: 'Switch Main Isolator to OFF (DOWN), apply red LOTO lockout padlock, and verify dead circuit state.',
              textZu: 'Cisha i-Isolator enkulu (PHANSI), ufake ingidi ebovu ye-LOTO, uqinisekise ukuthi kagesi uwile.',
              isCorrect: true,
              isSafetyCritical: true,
              explanation: 'Lockout-Tagout (LOTO) is mandatory under South African OHSA standards to prevent fatal electrocution from unexpected line energization.',
              explanationZu: 'I-LOTO iyisimfanelo phansi komthetho we-OHSA e-South Africa ukuvikela ingozi yokushiswa kagesi.',
              realWorldConsequence: 'Main DB board safely isolated! Busbars locked out and ready for voltage testing.',
              realWorldConsequenceZu: 'I-DB board iphephile! Kagesi ucishiwe futhi kusekulungele ukuhlolwa.',
              xpReward: 60,
            },
            {
              id: 'c_elec_1_2',
              text: 'Use bare metal pliers to force the tripped 20A breaker UP while main isolator stays ON.',
              textZu: 'Sebenzisa i-pliers yensimbi ukuyiphusha ngenkani le-breaker phezulu kagesi uxhunyiwe.',
              isCorrect: false,
              isSafetyCritical: true,
              explanation: 'Forcing a tripped breaker back ON into an active short circuit causes an explosive arc flash fire.',
              explanationZu: 'Ukuyiphusha ngenkani le-breaker kuxhuma i-short circuit kubangele umlilo nomsebe kagesi.',
              realWorldConsequence: 'CRITICAL SAFETY FAILURE: Arc flash explosion! Severe injury hazard.',
              realWorldConsequenceZu: 'UKUWA KWEZOKUPHEPHA: Ukudubula nomlilo kagesi!',
              xpReward: 0,
            },
          ],
        },
        hint: 'Switch Main Isolator OFF and attach Lockout-Tagout (LOTO) safety padlocks.',
        hintZu: 'Cisha i-Main Isolator ufake i-LOTO safety padlock.',
      },
      {
        stepId: 2,
        title: 'Step 2: Multimeter Voltage Verification & Faulty Appliance Isolation',
        titleZu: 'Inyathelo 2: Ukuhlola Amandla Kagesi Nge-Multimeter',
        objective: 'Use a 600V CAT III Digital Multimeter to test zero voltage on busbars, then unplug room appliances one by one.',
        objectiveZu: 'Sebenzisa mitha e-Multimeter ukuhlola ukuthi kagesi uwile yini, bese ukhipha izinto zikagesi ngazinye kumpompi.',
        environmentName: 'DB Board Busbar & Appliance Outlets',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_plug_outlets',
            name: 'Room Plug Circuit Outlets & Kettle',
            nameZu: 'Amaplagi Egumbi Neketela',
            category: 'electrical_fixture',
            status: 'faulty',
            label: 'Plug Socket (Damaged Element Kettle Plugged In)',
            labelZu: 'I-Socket Yeplagi (Iketela Elilimalele Kulo)',
            icon: 'AlertTriangle',
            position: { x: 45, y: 40, z: 0 },
            inspectText: 'A stainless-steel electric kettle with a shorted heating element is plugged into socket B.',
            inspectTextZu: 'Iketela kagesi eline-short circuit xhunywe emudulwini.',
          },
        ],
        availableTools: [
          {
            id: 'tool_digital_multimeter',
            name: '600V CAT III Digital Multimeter',
            nameZu: 'I-Digital Multimeter 600V CAT III',
            category: 'tools',
            description: 'Measures AC voltage (0V to 600V) and continuity (Ohms).',
            descriptionZu: 'Ibala amandla kagesi nosimende ngemitha.',
            icon: 'Zap',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_digital_multimeter',
        decisionPoint: {
          id: 'dec_elec_2',
          title: 'Multimeter confirms 0V on busbars. What is the systematic procedure to find why the 20A breaker kept tripping?',
          titleZu: 'Imitha iqinisekisa ukuthi amandla kagesi awe ku-0V. Uyithola kanjani into edala i-breaker ukuthatha i-trip?',
          prompt: 'Circuit breakers trip when total current exceeds rated capacity (e.g. 20 Amps) or when a dead short circuit exists.',
          promptZu: 'Izicishisi zikagesi zizicisha uma into inemibhaza enekhaza noma e-short circuit.',
          choices: [
            {
              id: 'c_elec_2_1',
              text: 'Unplug all appliances on the plug circuit (including shorted kettle), check cable insulation, then test circuit continuity.',
              textZu: 'Khipha zonke izinto kagesi kule-plug circuit (kuhlanganise neketela), uhlole nomcinga kagesi.',
              isCorrect: true,
              explanation: 'Unplugging loads isolates whether the fault is in the fixed house wiring or a defective portable appliance.',
              explanationZu: 'Ukukhipha izinto kukutshela ukuthi inkinga isezintamboni zasemudulwini noma kuyo intonto ethile kagesi.',
              realWorldConsequence: 'Fault isolated! The kettle element was short-circuited to earth. Wall wiring is healthy.',
              realWorldConsequenceZu: 'Inkinga itholakele! Iketela kagesi liyilo elidala i-short circuit. Intambo yesiliva iphephile.',
              xpReward: 60,
            },
            {
              id: 'c_elec_2_2',
              text: 'Replace 20A breaker with a huge 60A breaker so it won’t trip anymore when the kettle is plugged in.',
              textZu: 'Shintsha i-breaker ye-20A ufake eguqulwe yaba yisayizi enkulu ye-60A.',
              isCorrect: false,
              explanation: 'Over-sizing circuit breakers allows excessive heat in 2.5mm house wires, melting insulation and starting structure fires.',
              explanationZu: 'Ukufaka i-breaker enkulu kunakho kucobhoza izintambo zasemudulwini zishiye ngomlilo.',
              realWorldConsequence: 'FIRE HAZARD: Wall wiring melts due to excessive current overload.',
              realWorldConsequenceZu: 'INGANENI YOMLILO: Izintambo emudulwini ziyanqamuka ngomlilo.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Unplug all portable appliances to isolate external short circuits from house wiring.',
        hintZu: 'Khipha zonke izinto kagesi ukuze uthole into ene-short circuit.',
      },
      {
        stepId: 3,
        title: 'Step 3: Fault Resolution, LOTO Removal & Breaker Reset',
        titleZu: 'Inyathelo 3: Ukuyisusa Ingidi Nokuvula Kagesi',
        objective: 'Remove LOTO padlock, turn Main Isolator ON, reset the 20A circuit breaker, and verify power restoration.',
        objectiveZu: 'Susa ingidi ye-LOTO, uvule i-Main Isolator, uphushele phezulu i-circuit breaker, ubheke kagesi.',
        environmentName: 'Restored Electrical DB Board Panel',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_restored_db',
            name: 'Restored DB Panel',
            nameZu: 'I-DB Panel Ilungisiwe',
            category: 'electrical_fixture',
            status: 'resolved',
            label: 'All Breakers Operational (ON)',
            labelZu: 'Zonke I-Breakers Ziyasebenza (VULEKILE)',
            icon: 'CheckCircle2',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Main Isolator ON, Earth Leakage ON, 20A Plug CB reset and holding steadily without tripping.',
            inspectTextZu: 'I-Main Isolator ne-Earth Leakage nemishini kagesi kusebenza kahle ngaphandle kokuthatha i-trip.',
          },
        ],
        availableTools: [
          {
            id: 'tool_lockout_padlock',
            name: 'LOTO Safety Lockout Hasps & Red Padlock',
            nameZu: 'Ingidi Ye-Lockout Ebovu',
            category: 'safety',
            description: 'Unlock and remove LOTO padlock.',
            descriptionZu: 'Susa ingidi ye-LOTO.',
            icon: 'ShieldCheck',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_lockout_padlock',
        decisionPoint: {
          id: 'dec_elec_3',
          title: 'With defective kettle removed, how do you safely restore power to the customer household?',
          titleZu: 'Kuthe ngoba iketela le-short seli khishiwe, uyivula kanjani i-DB board ngokuphepha?',
          prompt: 'Remove LOTO tag, re-engage Main Isolator, and push the 20A breaker handle to full OFF before clicking to ON.',
          promptZu: 'Khipha i-tag, uvule i-Isolator enkulu, bese ukhiphela i-breaker phansi ngokuphelele ngaphambi kokuphonsa phezulu.',
          choices: [
            {
              id: 'c_elec_3_1',
              text: 'Unlock LOTO, switch Main Isolator ON, push tripped 20A breaker handle fully DOWN to reset internal spring, then flip UP to ON.',
              textZu: 'Vula ingidi ye-LOTO, uvule i-Isolator enkulu, uphushele i-breaker PHANSI kuqala ukuze usethe i-spring, bese ufaka PHEZULU.',
              isCorrect: true,
              explanation: 'Circuit breakers feature a mechanical trip mechanism requiring a full reset to OFF position before they can re-latch ON.',
              explanationZu: 'I-circuit breaker idinga ukuphushelwa phansi ngokuphelele kuqala ukuze yephuke i-spring ngaphambi kokuphushwa phezulu.',
              realWorldConsequence: 'SUCCESS! 20A breaker holds steadily. Household power fully restored. Electrical micro-credential logged.',
              realWorldConsequenceZu: 'IMPUMELELO! Breaker imi kahle phezulu. Kagesi emudulwini ubuye kahle emsebenzini!',
              xpReward: 100,
            },
            {
              id: 'c_elec_3_2',
              text: 'Leave LOTO padlock on the panel and tell customer to live in dark without power.',
              textZu: 'Shiya ingidi e-panel umtshele ukuthi ahlale ebumnyameni.',
              isCorrect: false,
              explanation: 'Leaving LOTO installed blocks customer access to functional circuits.',
              explanationZu: 'Ukushiya ingidi kuvimba umakhasimende ekuthole kagesi wakhe.',
              realWorldConsequence: 'Customer remains without electricity.',
              realWorldConsequenceZu: 'Umakhasimende uhlala engenakagesi.',
              xpReward: 0,
            },
          ],
        },
        hint: 'Reset tripped breakers by pushing handles fully DOWN first, then flipping UP to ON.',
        hintZu: 'Phushela breaker PHANSI kuqala, bese uphushela PHEZULU.',
      },
    ],
  },

  // ==========================================
  // SIMULATION 6: AUTOMOTIVE (ENGINE CLICK NO-START & BATTERY)
  // ==========================================
  'sim_automotive_1': {
    id: 'sim_automotive_1',
    skillId: 'skill_automotive_basic',
    title: 'Automotive Engine No-Start & Battery Terminal Diagnosis',
    titleZu: 'Ukuhlola Imoto Engaqalisi Ngebhethri Ye-Car Garage',
    category: 'automotive',
    difficulty: 'Beginner',
    difficultyZu: 'Owasemva',
    estimatedDataMB: 0.8,
    estimatedMinutes: 8,
    iconName: 'Car',
    description: 'A sedan at a roadside garage gives a rapid "click-click-click" sound when turning the ignition key, but the starter motor fails to crank the engine. Test 12V lead-acid battery terminal voltage under load, clean heavily corroded lead terminals with baking soda wash, and restore starter current.',
    descriptionZu: 'Imoto e-garaji yenza umsindo we-click-click-click kodwa injini ingavuleki. Hlola amandla a-12V e-bhethri, usule amakhanda e-bhethri abolekile nge-wire brush, bese uqala imoto.',
    realWorldContext: 'Rapid starter clicking in vehicles usually indicates low battery voltage (<10.5V under load) or high electrical resistance from white lead-sulfate corrosion on terminal posts.',
    realWorldContextZu: 'Umsindo we-click-click emotweni ukhombisa ukuthi ibhethri liphantsi noma amakhanda e-bhethri anemvubelo emhlophe evimba kagesi.',
    steps: [
      {
        stepId: 1,
        title: 'Step 1: Vehicle Safety Securing & Voltage Diagnostic Test',
        titleZu: 'Inyathelo 1: Ukuphepha Nemilayezo Ye-Multimeter Kwi-Bhethri',
        objective: 'Apply handbrake, set gearbox to Neutral/Park, open bonnet, and test 12V battery terminal state with a digital multimeter.',
        objectiveZu: 'Cindezela i-handbrake, ufake i-gear ku-Neutral, uvule i-bonnet yemoto, uhlole ibhethri nge-multimeter.',
        environmentName: 'Garage Workshop Engine Bay',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_car_battery',
            name: '12V Lead-Acid Car Battery',
            nameZu: 'Ibhethri Lemoto 12V Lead-Acid',
            category: 'automotive_part',
            status: 'warning',
            label: '12V Battery (White Sulfation on Positive Terminal)',
            labelZu: 'Ibhethri 12V (Amasulfation amhlophe ekhanda)',
            icon: 'BatteryCharging',
            position: { x: 35, y: 40, z: 0 },
            inspectText: 'Positive (+) terminal post covered in heavy white/green lead-sulfate powder corrosion.',
            inspectTextZu: 'Ikhanda(+) le-bhethri ligcwele amaphuphu amhlophe abolekile amanye evimba kagesi.',
          },
          {
            id: 'obj_ignition_key',
            name: 'Ignition Switch Key',
            nameZu: 'Iki-Switch Ye-Ignition',
            category: 'controls',
            status: 'normal',
            label: 'Key Position: START (Rapid Clicking Sound)',
            labelZu: 'Iki: START (Umsindo we-Clicking)',
            icon: 'Key',
            position: { x: 70, y: 55, z: 0 },
            inspectText: 'Turning key to START produces rapid clicking from starter solenoid, but engine fails to turn over.',
            inspectTextZu: 'Ukuvula iki ku-START kwenza umsindo we-click-click engaphendukisi njini.',
          },
        ],
        availableTools: [
          {
            id: 'tool_multimeter',
            name: 'Digital Multimeter (12V DC Range)',
            nameZu: 'I-Digital Multimeter Tester',
            category: 'tools',
            description: 'Measures battery resting voltage vs starter crank voltage drops.',
            descriptionZu: 'Ibala amandla kagesi e-bhethri.',
            icon: 'Zap',
            isCorrectForStep: true,
          },
          {
            id: 'tool_wire_brush',
            name: 'Steel Battery Terminal Wire Brush & Spanner',
            nameZu: 'Isixubho Sensimbi Samakhanda e-Bhethri',
            category: 'tools',
            description: 'Scrapes away non-conductive lead-sulfate corrosion crust.',
            descriptionZu: 'Isula ukhoko olumhlophe emakhandeni e-bhethri.',
            icon: 'Wrench',
          },
        ],
        requiredToolId: 'tool_multimeter',
        decisionPoint: {
          id: 'dec_auto_1',
          title: 'Multimeter reads 12.6V resting on battery posts, BUT drops to 8.2V across the corroded cable clamp when key is turned. What does this reveal?',
          titleZu: 'Imitha ifunda 12.6V kwi-bhethri, kodwa yehla ku-8.2V kwi-cable ngesikhathi se-key. Yini leyo nkinga?',
          prompt: 'A large voltage drop across terminal clamps proves extreme electrical resistance caused by corrosive lead-sulfate crust.',
          promptZu: 'Ukuhla kwamandla kagesi phakathi kwe-cable ne-bhethri kutshela ukuthi ukhoko luvimba kagesi.',
          choices: [
            {
              id: 'c_auto_1_1',
              text: 'High electrical resistance on battery terminals! Corroded posts must be disconnected and cleaned with a wire brush.',
              textZu: 'Inkinga ikukhoko oluvimba kagesi! Amakhanda e-bhethri adinga ukuhlanjwa ngesixubho sensimbi.',
              isCorrect: true,
              explanation: 'Lead-sulfate buildup acts as an insulator, dropping cranking current from 200 Amps down to 30 Amps and causing starter clicking.',
              explanationZu: 'Ukhoko luvimba amandla awo-200 Amps adingwa yi-starter motor ukujikisa injini.',
              realWorldConsequence: 'Diagnosis confirmed! High contact resistance pinpointed on positive terminal clamp.',
              realWorldConsequenceZu: 'Ukuhlola kuqinisekisiwe! Inkinga ivela ekhulwini e-positive terminal.',
              xpReward: 60,
            },
            {
              id: 'c_auto_1_2',
              text: 'The engine is permanently seized and must be completely replaced with a new R30,000 engine block.',
              textZu: 'Injini ilimale ngokuphelele adinga ukushintshwa ngenjini entsha ewu-R30,000.',
              isCorrect: false,
              explanation: 'Misdiagnosing dirty battery terminals as a seized engine wastes customer money unnecessarily.',
              explanationZu: 'Ukucabanga ukuthi injini ifile ngenxa ye-bhethri elimatasa kamosha imali yamakhasimende.',
              realWorldConsequence: 'Faulty diagnosis leads to massive unnecessary expenditure.',
              realWorldConsequenceZu: 'Ukuvunyelwa kunganikezi mpendulo eziyikho.',
              xpReward: 0,
            },
          ],
        },
        hint: 'High voltage drops across cable clamps indicate corroded terminal connections.',
        hintZu: 'Ukuhla kwamandla kagesi e-clamp kutshela ukuthi terminal iyabola.',
      },
      {
        stepId: 2,
        title: 'Step 2: Battery Terminal Cleaning & Protective Grease Application',
        titleZu: 'Inyathelo 2: Ukuhlanza Amakhanda e-Bhethri Nokufaka I-Grease',
        objective: 'Disconnect negative cable first, scrub lead posts with a wire brush using baking soda wash, reconnect clamps, and apply petroleum jelly.',
        objectiveZu: 'Khipha intambo e-negative kuqala, usule nge-wire brush ne-baking soda, uhlanganise kabusha ufake ne-petroleum jelly.',
        environmentName: 'Battery Post Servicing View',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_cleaned_posts',
            name: 'Cleaned Lead Battery Post',
            nameZu: 'Ikhanda Le-Bhethri Elisuliwe',
            category: 'automotive_part',
            status: 'resolved',
            label: 'Shiny Metallic Lead Post & Clamp',
            labelZu: 'Ikhanda Lomsila Elikhazimulayo',
            icon: 'CheckCircle2',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Lead posts scrubbed down to bare metal. Zero sulfation remaining. Tightened with 10mm spanner.',
            inspectTextZu: 'Ikhanda lisuliwe, likhazimula kahle ngaphandle kwevubelo.',
          },
        ],
        availableTools: [
          {
            id: 'tool_wire_brush',
            name: 'Steel Battery Terminal Wire Brush & Spanner',
            nameZu: 'Isixubho Sensimbi Samakhanda e-Bhethri',
            category: 'tools',
            description: 'Scrapes away non-conductive oxide layers.',
            descriptionZu: 'Isula ivubelo kagesi emakhandeni.',
            icon: 'Wrench',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_wire_brush',
        decisionPoint: {
          id: 'dec_auto_2',
          title: 'What is the correct terminal disconnection order when servicing a 12V automotive battery?',
          titleZu: 'Uyikhipha kanjani imicu ye-bhethri ngokuphepha?',
          prompt: 'Disconnecting NEGATIVE (-) first prevents accidental short-circuit sparks if your metal wrench touches the steel car body.',
          promptZu: 'Ukukhipha i-NEGATIVE (-) kuqala kuvimbela umsebe kagesi uma i-spanner ithinta isiliva lemoto.',
          choices: [
            {
              id: 'c_auto_2_1',
              text: 'Disconnect NEGATIVE (-) first, then POSITIVE (+). Scrub posts clean, reconnect POSITIVE (+) first, then NEGATIVE (-), and coat with petroleum jelly.',
              textZu: 'Khipha i-NEGATIVE (-) kuqala, bese i-POSITIVE (+). Hlanza amakhanda, uxhume i-POSITIVE (+) kuqala, bese i-NEGATIVE (-), ufake ne-grease.',
              isCorrect: true,
              isSafetyCritical: true,
              explanation: 'Disconnecting ground (-) first breaks the circuit loop, rendering the chassis neutral so spanners touching body metal cannot create short circuits.',
              explanationZu: 'Ukukhipha i-negative kuqala kuqeda umthamo kagesi esiliveni lemoto ukuze i-spanner ingadali imisebe.',
              realWorldConsequence: 'Terminals cleaned and re-connected safely without sparks! Full electrical conductivity restored.',
              realWorldConsequenceZu: 'Amakhanda e-bhethri ahlanzwe aphepha ngaphandle kwemisebe!',
              xpReward: 60,
            },
            {
              id: 'c_auto_2_2',
              text: 'Disconnect POSITIVE (+) first while resting a long metal wrench directly against the steel car chassis body.',
              textZu: 'Khipha i-POSITIVE (+) kuqala uhlale ne-spanner kwi-siliva lemoto.',
              isCorrect: false,
              isSafetyCritical: true,
              explanation: 'Touching a live positive wrench against grounded chassis steel creates a massive 400A dead short spark that can burst the battery.',
              explanationZu: 'Ukuthinta positive kwi-siliva lwe-car kucisha imisebe ye-400A eyingozi e-bhethri.',
              realWorldConsequence: 'CRITICAL SAFETY HAZARD: Massive short circuit spark welded wrench to chassis!',
              realWorldConsequenceZu: 'UKUWA KWEZOKUPHEPHA: Umsebe kagesi oshisa i-spanner kwi-chassis!',
              xpReward: 0,
            },
          ],
        },
        hint: 'Disconnect NEGATIVE (-) first, clean posts, reconnect POSITIVE (+) first, then NEGATIVE (-).',
        hintZu: 'Khipha i-NEGATIVE (-) kuqala, uxhume i-POSITIVE (+) kuqala ngemva kwekuhlanza.',
      },
      {
        stepId: 3,
        title: 'Step 3: Engine Crank Test & Alternator Charging Verification',
        titleZu: 'Inyathelo 3: Ukudlulisa Injini Nokuhlola I-Alternator',
        objective: 'Turn ignition key to START, verify immediate smooth engine crank, and check multimeter for 14.2V alternator charging output.',
        objectiveZu: 'Vula iki kwi-START, uthole ukuvuleka kwenjini kamnandi, uhlole ne-alternator eku-14.2V.',
        environmentName: 'Running Engine Bay Dashboard',
        format: 'PSEUDO_3D',
        objects: [
          {
            id: 'obj_running_engine',
            name: 'Running 1.6L Engine',
            nameZu: 'Injini Eseqala Ukuhamba 1.6L',
            category: 'automotive_part',
            status: 'resolved',
            label: 'Engine Purring smoothly (Multimeter: 14.2V Charging)',
            labelZu: 'Injini Iyahamba Kahle (Mitha: 14.2V Charging)',
            icon: 'CheckCircle2',
            position: { x: 50, y: 40, z: 0 },
            inspectText: 'Engine started instantly on first turn! Alternator is charging battery at 14.2V DC.',
            inspectTextZu: 'Injini iqale emsebenzini ngokushesha! I-Alternator ifaka kagesi omuhle 14.2V.',
          },
        ],
        availableTools: [
          {
            id: 'tool_multimeter',
            name: 'Digital Multimeter (12V DC Range)',
            nameZu: 'I-Digital Multimeter Tester',
            category: 'tools',
            description: 'Verifies 13.8V - 14.4V alternator charging rail output.',
            descriptionZu: 'Iqinisekisa ukuthi i-alternator ikhaza amandla awo-14.2V.',
            icon: 'Zap',
            isCorrectForStep: true,
          },
        ],
        requiredToolId: 'tool_multimeter',
        decisionPoint: {
          id: 'dec_auto_3',
          title: 'The engine cranked effortlessly and runs smoothly. Multimeter across battery terminals reads 14.2V with engine running. What does 14.2V signify?',
          titleZu: 'Injini ivuleke kahle. Imitha e-bhethri ifunda 14.2V ngenkathi injini ihamba. Kusho ukuthini i-14.2V?',
          prompt: 'A running alternator should output between 13.8V and 14.4V to recharge the battery while powering vehicle headlights and radio.',
          promptZu: 'I-Alternator ephilayo kufanele ifake 13.8V kuya ku-14.4V ukushaja ibhethri ngenkathi unamba imoto.',
          choices: [
            {
              id: 'c_auto_3_1',
              text: 'The alternator is functioning perfectly, charging the battery at healthy 14.2V voltage. Repair complete!',
              textZu: 'I-alternator isebenaza kahle kakhulu, ishaja ibhethri ku-14.2V. Umsebenzi uphelele!',
              isCorrect: true,
              explanation: '14.2V proves the alternator belt and diode bridge are recharging the 12V lead-acid battery during driving.',
              explanationZu: '14.2V iqinisekisa ukuthi i-alternator ishaja ibhethri kahle endleleni.',
              realWorldConsequence: 'SUCCESS! No-start problem permanently resolved. Automotive skill credential awarded!',
              realWorldConsequenceZu: 'IMPUMELELO! Imoto iqala kahle kakhulu! Ibheji lemoto lomsebenzi linikeziwe!',
              xpReward: 100,
            },
            {
              id: 'c_auto_3_2',
              text: '14.2V means the battery is exploding and the vehicle must be abandoned in the garage immediately.',
              textZu: '14.2V kusho ukuthi ibhethri lizodubula kumele ubaleke egaraji.',
              isCorrect: false,
              explanation: '13.8V to 14.4V is the normal healthy alternator charging window for 12V automotive systems.',
              explanationZu: '13.8V kuya ku-14.4V umthamo kagesi omuhle oshayela i-alternator.',
              realWorldConsequence: 'Misinterpretation causes unnecessary alarm.',
              realWorldConsequenceZu: 'Ukungasizakali unikeza incazelo engeyiyo.',
              xpReward: 0,
            },
          ],
        },
        hint: '13.8V to 14.4V with engine running confirms healthy alternator battery charging.',
        hintZu: '13.8V kuya ku-14.4V ngenkathi injini ihamba kuqinisekisa ukushaja omuhle kwe-alternator.',
      },
    ],
  },
};

